# Nome da aplicação
spring.application.name=service-users

# ==========================================
# CONFIGURAÇÃO ATUAL: Banco H2 em Memória (Para Testes Rápidos/Postman)
# ==========================================
spring.datasource.url=jdbc:h2:mem:ifsp_sports_users
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Console do H2 (Acessível em http://localhost:8080/h2-console)
spring.h2.console.enabled=true

# Estratégia de criação de tabelas e exibição de SQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==========================================
# CONFIGURAÇÃO FUTURA: Banco de Dados (MySQL) - COMENTADO PARA TESTE RÁPIDO
# ==========================================
#spring.datasource.url=jdbc:mysql://localhost:3306/ifsp_sports_users?createDatabaseIfNotExist=true&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=sua_senha_aqui


# ==========================================
# CONFIGURAÇÃO JWT
# ==========================================
jwt.secret=ifsp-competicoes-segredo-super-secreto-2024-chave-longa-para-seguranca
jwt.expiration=86400000