# Nome da aplicação
spring.application.name=service-users

# Configuração do Banco de Dados (MySQL) - COMENTADO PARA TESTE RÁPIDO
#spring.datasource.url=jdbc:mysql://localhost:3306/ifsp_sports_users?createDatabaseIfNotExist=true&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=sua_senha_aqui

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true